import type { PricingTier } from "./types";

export const pricingTiers: PricingTier[] = [
  {
    name: "Free",
    slug: "free",
    price: 0,
    annualPrice: 0,
    description: "Get your business listed and start being discovered by local pet owners.",
    features: [
      { text: "Basic business listing", included: true },
      { text: "Name, address & phone number", included: true },
      { text: "1 photo", included: true },
      { text: "Category placement", included: true },
      { text: "Up to 10 photos", included: false },
      { text: "Website link & Business hours", included: false },
      { text: "Remove competitor ads on profile", included: false },
      { text: "Analytics dashboard", included: false },
      { text: "Direct booking integration", included: false },
      { text: '"Paw-Verified" badge', included: false },
      { text: '"Best in Show" badge', included: false },
      { text: "Priority search placement", included: false },
    ],
    isPopular: false,
    ctaText: "Join the Pack — Free",
  },
  {
    name: "Standard",
    slug: "standard",
    price: 15,
    annualPrice: 12,
    description: "Take control of your reputation and stand out from free listings.",
    features: [
      { text: "Basic business listing", included: true },
      { text: "Name, address & phone number", included: true },
      { text: "Up to 10 photos & gallery", included: true },
      { text: "Category placement", included: true },
      { text: "Website link & Business hours", included: true },
      { text: "Remove competitor ads on profile", included: true },
      { text: "Analytics dashboard", included: true },
      { text: "Direct booking integration", included: false },
      { text: '"Paw-Verified" badge', included: false },
      { text: '"Best in Show" badge', included: false },
      { text: "Priority search placement", included: false },
    ],
    isPopular: false,
    ctaText: "Take Control",
  },
  {
    name: "Featured",
    slug: "featured",
    price: 29,
    annualPrice: 24,
    description: "Get the visibility boost that fills your appointment book.",
    features: [
      { text: "Everything in Standard", included: true },
      { text: "Unlimited photos & video", included: true },
      { text: '"Paw-Verified" badge', included: true },
      { text: "Top-tier search placement (Rotated)", included: true },
      { text: "Direct booking integration", included: true },
      { text: "Review highlights & Social links", included: true },
      { text: '"Best in Show" badge', included: false },
      { text: "#1 placement in your area", included: false },
      { text: "Lead notifications & inbox", included: false },
      { text: "Competitor insights", included: false },
      { text: "Homepage spotlight", included: false },
    ],
    isPopular: true,
    ctaText: "Become a Top Dog",
  },
  {
    name: "Premium",
    slug: "premium",
    price: 50,
    annualPrice: 40,
    description: "Maximum visibility. Maximum leads. The full Top Dog experience.",
    features: [
      { text: "Everything in Featured", included: true },
      { text: '"Best in Show" badge', included: true },
      { text: "#1 placement in your area", included: true },
      { text: "Lead notifications & inbox", included: true },
      { text: "Competitor insights", included: true },
      { text: "Homepage spotlight rotation", included: true },
      { text: "Dedicated profile page", included: true },
      { text: "Blog spotlight feature", included: true },
      { text: "Priority customer support", included: true },
      { text: "Monthly performance report", included: true },
      { text: "Custom branding options", included: true },
    ],
    isPopular: false,
    ctaText: "Unleash Full Power",
  },
];

