#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate the Maui compare index.html from the directory layout.

Layout expected:
  _compare/
    <slug-1>/
      gemini.png
      openai.png
    <slug-2>/
      ...

Usage:
  maui-compare-index.py <path-to-_compare-dir>
"""
from __future__ import annotations

import html
import sys
from datetime import datetime
from pathlib import Path


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: maui-compare-index.py <_compare-dir>", file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).resolve()
    if not root.is_dir():
        print(f"not a directory: {root}", file=sys.stderr)
        return 2

    # Collect slugs (subdirs that contain at least one of gemini.png/openai.png)
    slugs = []
    for child in sorted(root.iterdir()):
        if not child.is_dir():
            continue
        if (child / "gemini.png").exists() or (child / "openai.png").exists():
            slugs.append(child.name)

    # Also collect legacy flat files (e.g. older v1/v2/v3 directories) — link to them
    legacy_dirs = sorted(
        d for d in root.iterdir()
        if d.is_dir() and d.name.startswith("v") and (d / "index.html").exists()
    )

    rows = []
    for slug in slugs:
        gemini_path = f"{slug}/gemini.png"
        openai_path = f"{slug}/openai.png"
        rows.append(f"""
<h2>{html.escape(slug)}</h2>
<div class="row">
  <div class="card anchor"><img src="../00-maui-main.png" alt="anchor"><div class="label">Style anchor</div><div class="meta">00-maui-main.png</div></div>
  <div class="card"><img src="{gemini_path}" alt="gemini" onerror="this.outerHTML='<div class=missing>not generated</div>'"><div class="label">Gemini</div><div class="meta">via ads skill</div></div>
  <div class="card"><img src="{openai_path}" alt="openai" onerror="this.outerHTML='<div class=missing>not generated</div>'"><div class="label">OpenAI</div><div class="meta">gpt-image skill</div></div>
  <div class="card promote"><div class="label">Promote winner</div><pre class="cmd">mv _compare/{slug}/&lt;gemini\\|openai&gt;.png \\\n  maui-{slug}-blog.png</pre></div>
</div>
""")

    legacy_links = ""
    if legacy_dirs:
        legacy_links = "<nav class='legacy'>Older runs: " + " · ".join(
            f'<a href="{d.name}/index.html">{d.name}</a>' for d in legacy_dirs
        ) + "</nav>"

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    print(f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Maui Blog Image Compare</title>
<style>
  body {{ font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 32px; background: #fafaf7; color: #2a2218; }}
  h1 {{ margin: 0 0 8px; font-size: 22px; }}
  p.lead {{ margin: 0 0 24px; color: #6b5f4f; max-width: 780px; }}
  h2 {{ margin: 36px 0 12px; font-size: 18px; border-top: 1px solid #e5dfd2; padding-top: 24px; font-family: "SF Mono", Menlo, monospace; }}
  .row {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; }}
  .card {{ background: #fff; border: 1px solid #e5dfd2; border-radius: 12px; padding: 12px; text-align: center; }}
  .card img {{ width: 100%; height: auto; aspect-ratio: 1/1; object-fit: contain; background: #fff; border-radius: 8px; }}
  .card .label {{ font-weight: 600; margin-top: 8px; font-size: 12px; }}
  .card .meta {{ color: #8a7d6a; font-size: 11px; margin-top: 2px; }}
  .anchor {{ background: #f0fff4; border-color: #cce5d4; }}
  .anchor .label::before {{ content: "⚓ "; }}
  .promote {{ background: #fffbed; border-color: #f0e6c8; display: flex; flex-direction: column; justify-content: center; align-items: stretch; }}
  .promote .cmd {{ font-size: 11px; background: #2a2218; color: #f5ebd8; padding: 10px; border-radius: 6px; text-align: left; white-space: pre-wrap; word-break: break-all; margin: 8px 0 0; }}
  .missing {{ color: #c1272d; font-style: italic; padding: 60px 0; background: #fff5f5; border-radius: 8px; font-size: 12px; }}
  nav.legacy {{ font-size: 12px; color: #8a7d6a; margin-bottom: 12px; }}
  nav.legacy a {{ color: #C1272D; text-decoration: none; margin-right: 12px; }}
  .meta-stamp {{ font-size: 11px; color: #8a7d6a; }}
</style>
</head>
<body>

<h1>Maui Blog Image Compare</h1>
<p class="lead">Side-by-side review of generated Maui blog illustrations. Each row: canonical style anchor (<code>00-maui-main.png</code>), Gemini variant, OpenAI variant, and the promotion command. Generated by <code>scripts/maui-blog-image.sh</code>.</p>
<p class="meta-stamp">Index generated {now}</p>
{legacy_links}
{''.join(rows) if rows else '<p><em>No scenes generated yet. Run scripts/maui-blog-image.sh &lt;slug&gt; "&lt;scene&gt;".</em></p>'}

</body>
</html>""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
